/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.3.1/userguide/multi_project_builds.html
 */

rootProject.name = "po-arbeidsoppfolging-meta"

includeBuild("felles/pus-decorator")
includeBuild("felles/pus-nais-java-app")
includeBuild("felles/pto-iac")
includeBuild("felles/pto-playbook")
includeBuild("felles/pto-proxy")
includeBuild("felles/pto-frontend")
includeBuild("felles/pto-aivia")
includeBuild("felles/pto-admin")
includeBuild("felles/frontendlogger")
includeBuild("felles/common-java-modules")
includeBuild("felles/veilarbproxy")
includeBuild("dab/veilarbaktivitet")
includeBuild("dab/aktivitetsplan")
includeBuild("dab/arbeidsrettet-dialog")
includeBuild("dab/start-samtale")
includeBuild("dab/veilarbdialog")
includeBuild("dab/veilarbdirigent")
includeBuild("dab/veilarblest")
includeBuild("dab/veilarbmalverk")
includeBuild("dab/veilarbvarsel")